### ISSUE TITLE
Mitigated by using https

### ISSUE THREAD

**Issue by samrocketman** [jlblatt/AwSnap#1]
Visiting this (crash)

http://www.reddit.com/r/webdev/comments/31kumu/this_post_crashes_chrome/

vs visiting this (no crash)

https://www.reddit.com/r/webdev/comments/31kumu/this_post_crashes_chrome/

It seems to not encounter the bug when HTTPS is used.

**Comment by jlblatt** [comment]
Yup, you are correct, readme was updated to reflect this
